volumes:
  dev_postgres_data: {}
  dev_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/dev/django/Dockerfile
    image: webcast_dev_django
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.dev/.env
    command: /start
    ports: ["8000:5000"]

  postgres:
    build:
      context: .
      dockerfile: ./compose/dev/postgres/Dockerfile
    image: webcast_dev_postgres
    volumes:
      - dev_postgres_data:/var/lib/postgresql/data:Z
      - dev_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.dev/.env

  redis:
    image: redis:7.0

  celeryworker:
    <<: *django
    image: webcast_dev_celeryworker
    command: /start-celeryworker
    ports: []

  celerybeat:
    <<: *django
    image: webcast_dev_celerybeat
    command: /start-celerybeat
    ports: []

  flower:
    <<: *django
    image: webcast_dev_flower
    command: /start-flower
    ports: []
