# Generated by Django 3.2.16 on 2023-01-21 13:26

import django.contrib.postgres.fields.citext
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_detail', models.CharField(max_length=30)),
                ('email', django.contrib.postgres.fields.citext.CIEmailField(max_length=254, verbose_name='email address')),
                ('mobile_number', models.IntegerField(max_length=12)),
            ],
        ),
    ]
